//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Validators {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
		
		protected System.Web.UI.WebControls.Label nameLbl;
		
		protected System.Web.UI.WebControls.TextBox nameTxt;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator ReqFV1;
		
		protected System.Web.UI.WebControls.Label firstNameLbl;
		
		protected System.Web.UI.WebControls.TextBox firstNameTxt;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator ReqFV2;
		
		protected System.Web.UI.WebControls.Label emilLbl;
		
		protected System.Web.UI.WebControls.TextBox emailTxt;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator ReqFV3;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator RegexpV1;
		
		protected System.Web.UI.WebControls.Label passwordLbl;
		
		protected System.Web.UI.WebControls.TextBox passwordTxt;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator ReqFV4;
		
		protected System.Web.UI.WebControls.Label confirmPasswordLbl;
		
		protected System.Web.UI.WebControls.TextBox confirmPasswordTxt;
		
		protected System.Web.UI.WebControls.CompareValidator CompV1;
		
		protected System.Web.UI.WebControls.Label yearLbl;
		
		protected System.Web.UI.WebControls.DropDownList yearDD;
		
		protected System.Web.UI.WebControls.CompareValidator CompV2;
		
		protected System.Web.UI.WebControls.Label birthDateLbl;
		
		protected System.Web.UI.WebControls.TextBox birthDateTxt;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator ReqFV5;
		
		protected System.Web.UI.WebControls.CompareValidator CompV4;
		
		protected System.Web.UI.WebControls.Label genderLbl;
		
		protected System.Web.UI.WebControls.RadioButtonList genderRB;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator ReqFV6;
		
		protected System.Web.UI.WebControls.Label ageLbl;
		
		protected System.Web.UI.WebControls.TextBox ageTxt;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator ReqFV7;
		
		protected System.Web.UI.WebControls.RangeValidator RangeV1;
		
		protected System.Web.UI.WebControls.CustomValidator CustomV1;
		
		protected System.Web.UI.WebControls.Button saveBtn;
	}
}
